### ISSUE TITLE
哪个链接能被Surge订阅?

### ISSUE THREAD

**Issue by CorrectRoadH** [vvbbnn00/WARP-Clash-API#13]
我看README上面写着支持Surge，我想问一下哪个能被Surge订阅👀

没有的话，我等等开个PR了
![CleanShot 2024-01-27 at 23 32 48@2x](https://github.com/vvbbnn00/WARP-Clash-API/assets/29306285/accdc553-8d7a-4d02-b036-f6632fdd72c3)

**Comment by vvbbnn00** [comment]
不好意思，我搞错了，以为Surge是默认支持Clash订阅的😂

**Comment by CorrectRoadH** [comment]
> 不好意思，我搞错了，以为Surge是默认支持Clash订阅的😂

行的，我在写了，预计明天能提一个PR。

**Comment by vvbbnn00** [comment]
> > 不好意思，我搞错了，以为Surge是默认支持Clash订阅的😂
> 
> 好的，感谢大佬回复，我觉得我可以写一个PR来实现这个功能，预计明天能提一个PR。这个项目是一个很棒的项目👍


感谢你的支持！

**Comment by vvbbnn00** [comment]
分支已经合并，感谢您对本项目的贡献！
