### ISSUE TITLE
能否支持一下圈X订阅

### ISSUE THREAD

**Issue by jae-jae** [vvbbnn00/WARP-Clash-API#130]
能否支持一下圈X订阅, 试了各种订阅地址导入圈X都报错：
<img width="513" alt="image" src="https://github.com/vvbbnn00/WARP-Clash-API/assets/5620429/2b8d94a8-4448-4b56-b844-22a3c4a5397b">

**Comment by vvbbnn00** [comment]
目前[Quantumult-X](https://github.com/crossutility/Quantumult-X)不支持wireguard协议
