### ISSUE TITLE
请求支持使用自己的配置文件

### ISSUE THREAD

**Issue by histion** [vvbbnn00/WARP-Clash-API#140]
使用惯了自己的配置文件，用这个生成的配置文件有点不习惯，能否支持上传自己的配置模板进行生成

**Comment by histion** [comment]
但如果使用https://sub.xeton.dev/此类订阅转换将生成的订阅转换成自己模板订阅的话会导致无法访问任何被墙的网站。

**Comment by vvbbnn00** [comment]
实际上先前的版本已经支持您使用自己的配置文件（即修改`config/clash.json`文件）

在目前的最新版中，我们更换了配置文件的解析器，使得即使在`clash.json`中填入`yaml`格式的内容，也能够正常解析：https://github.com/vvbbnn00/WARP-Clash-API/pull/146

**Comment by histion** [comment]
好吧，可能是我描述的不够准确，其实我的意思是想要导入这种模板https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/config/ACL4SSR_AdblockPlus.ini，然后生成订阅文件
