### ISSUE TITLE
[Bug]{"code":400,"message":"License key is required" 

### ISSUE THREAD

**Issue by jonnyman12345** [vvbbnn00/WARP-Clash-API#144]
curl -X POST http://192.168.60.63:21001/api/account/update_license?key=Yc1234567890 -H "Content-Type: application/json" -d "{\"9r3Cto75-d7451acZ-LY6kB012\": \"9r3Cto75-d7451acZ-LY6kB012\"}"
{"code":400,"message":"License key is required"}

**Comment by vvbbnn00** [comment]
{"license_key": "9r3Cto75-d7451acZ-LY6kB012"}"
