### ISSUE TITLE
[Bug] Loon Lite 无法使用

### ISSUE THREAD

**Issue by katorly** [vvbbnn00/WARP-Clash-API#150]
**注:** 本人并不知道 Loon 与 Loon Lite 在识别订阅格式的方面有何不同。  

**📜 检查表**

- [x] 我已了解目前issue主要处理`bug`和接收`feature request`
  ，其他类型的问题（如操作、配置问题，客户端问题等）应发布在[discussions](https://github.com/vvbbnn00/WARP-Clash-API/discussions)
  中，否则该issue可能被关闭。
- [x] 我确认这是由本项目引起的bug，而非Cloudflare
  WARP自身服务限制、客户端不支持等其他原因造成的（若不确定，请同样发布在[discussions](https://github.com/vvbbnn00/WARP-Clash-API/discussions)）。
- [x] 我已核实该bug尚未在其他issue中被提及。

**Bug描述**

在 #136 中，增加了 iOS 上对 Loon 软件的支持。  
但我在 iPadOS 上使用 Loon Lite 添加订阅时，显示无法找到任何节点，添加失败。  

可以看到服务端已接收到软件的请求：  
![2024-03-15_234236](https://github.com/vvbbnn00/WARP-Clash-API/assets/70022443/705b0b2e-c7c0-426a-8461-232373f62f16)

但却显示没有找到任何节点：  
![IMG_3120](https://github.com/vvbbnn00/WARP-Clash-API/assets/70022443/e363668a-cfa5-4528-9068-77bc1ce87eea)

多次重新部署仍然出现此问题，说明可能尚不支持 Loon Lite。

**复现步骤**

向 Loon Lite 中通过链接添加 WARP Clash API 订阅节点。  

**环境信息**

- 设备型号：iPad Pro 2020

- 系统版本：iPadOS 16.6

- 软件名称：Loon Lite

- 软件版本：1.0.7

- 订阅类型：Loon

- 出现问题时项目的 `Commit Hash`：52e9f070bdfb75c1d8a5f50d682f6422149c1ef4

**额外信息**

- 部署的项目已为最新版本
- Loon Lite 软件已更新至最新版本
- 从订阅链接获取节点时网络畅通
- 可在 Clash Meta 中正常使用此项目的订阅
- 使用的 Loon Lite 可以正常添加其它订阅

**Comment by vvbbnn00** [comment]
根据appstore的官方介绍，Loon Lite似乎不支持wireguard：
![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/46409975/c83df797-dcdc-47c4-83ba-ff9284f49c44)

作为对比，以下是loon的介绍：
![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/46409975/758d57a6-d193-4cea-9f49-d50ae7734fcc)
