### ISSUE TITLE
你的ip是什么ip啊

### ISSUE THREAD

**Issue by hicaicai** [vvbbnn00/WARP-Clash-API#152]
http://你的IP:21001

你的ip是什么ip啊
小白看不太懂

http://127.0.0.1:21001/api/clash?best=false&randomName=true&proxyFormat=full&ipv6=true
我得到这个链接，但是无法下载节点，把上面的链接打开提示{"code":403,"message":"Unauthorized"}
请问这是什么意思

**Comment by hicaicai** [comment]
解决了

**Comment by yzwou** [comment]
> 解决了

可以问一下是如何解决的吗
