### ISSUE TITLE
导出订阅的节点信息应该如何修改？

### ISSUE THREAD

**Issue by histion** [vvbbnn00/WARP-Clash-API#154]
用warpclash导出的订阅在clash verge和手机端的clashmeta中（其他clash未测试）订阅会有到期日期和剩余流量两个数据，流量数据对不上我自己的warp的剩余流量，日期也是9999年，想知道这个信息应该在哪里修改
![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/65994410/73c724bf-3e2a-4f87-ab59-0da37e1be6dd)

**Comment by vvbbnn00** [comment]
日期可以在此处修改`expire`参数实现：
https://github.com/vvbbnn00/WARP-Clash-API/blob/0b312f8718c4206e049e6bf0f36c6646bef4d0ff/services/web_service.py#L193-L197

剩余流量是从`Cloudflare API`获取的，不建议修改

**Comment by histion** [comment]
> 日期可以在此处修改`expire`参数实现：
> 
> https://github.com/vvbbnn00/WARP-Clash-API/blob/0b312f8718c4206e049e6bf0f36c6646bef4d0ff/services/web_service.py#L193-L197
> 
> 剩余流量是从`Cloudflare API`获取的，不建议修改

感谢
