### ISSUE TITLE
请问生成的节点都为国内ip是否正常？

### ISSUE THREAD

**Issue by Asakushen** [vvbbnn00/WARP-Clash-API#156]
执行优选操作后发现生成的订阅信息全部为和我所在地一致的ip，这是正常现象吗？

**Comment by HynoR** [comment]
正常，因为cf是根据你入口ip给你分配的地址。
并且支持所有国家和地区，甚至包括...
![IMG_20240325_234352_551](https://github.com/vvbbnn00/WARP-Clash-API/assets/20227709/54e3ef70-a033-4e0f-82dc-514adeb07d67)
