### ISSUE TITLE
[Bug] ip优选功能似乎不正常

### ISSUE THREAD

**Issue by gaofashao** [vvbbnn00/WARP-Clash-API#162]
**Bug描述**

1、软件版本:dockerhub 3月26日最新版本，使用命令前已更新镜像到最新
2、在容器内执行/app目录下执行python3 app.py optimize时，命令报错中断。检查/app/config下的result.csv文件的更新时间发现也是没更新。详细日志请查看截图。
3、容器无ipv6环境，可能是筛选ipv6节点时出错导致无法继续

**截屏**

![Screenshot_2024-03-26-01-32-39-95_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/vvbbnn00/WARP-Clash-API/assets/39672493/6535774f-deeb-4414-a82f-35da3068ed26)

**环境信息**

- 设备型号：rk3399

- 系统版本：lxc容器安装casaos

**Comment by vvbbnn00** [comment]
你好，
`IPv4`优选和`IPv6`是独立的，理论上相互不影响。
根据您提供的信息，似乎无法复现相关问题：

![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/46409975/5206394b-dc4e-4268-a94a-7b73ad3b5d20)

![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/46409975/db38f6e2-fb49-4e0b-8836-ff445322a430)

![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/46409975/f3277d9c-a02d-4416-a070-7f6a0632c36e)

**Comment by mhqschen** [comment]
我在容器内部执行python3 app.py optimize后，也遇到了报错，看这样子没有测速。但是result.csv文件是有更新的。


```
745dc8430e38:/app# python3 app.py optimize
Getting IPv4 entrypoints
./scripts/get_entrypoints.sh: line 22: ulimit: open files: cannot modify limit: Operation not permitted
CloudflareWarpSpeedTest

1000 / 1000 [----------------------------------------------------------------------------------------------------------------------------------------] Available: 447  

IP:Port                                     Loss     Latency   
162.159.192.91:939                           0%      251.41    
188.114.97.241:8319                          0%      268.82    
188.114.99.20:1701                           0%      275.12    
188.114.98.232:945                           0%      276.43    
188.114.96.231:2408                          0%      285.81    
188.114.98.237:955                           0%      294.69    

Complete speed test results have been written to the result.csv file.
Getting IPv6 entrypoints
./scripts/get_entrypoints.sh: line 22: ulimit: open files: cannot modify limit: Operation not permitted
CloudflareWarpSpeedTest

1000 / 1000 [------------------------------------------------------------------------------------------------------------------------------------------] Available: 0  

[Info] The total number of IP addresses in the complete speed test results is 0, so skipping the output.
mv: can't rename 'result.csv': No such file or directory
```
