### ISSUE TITLE
[Bug]配置文件只有No entrypoints available. Please try again later.这行内容

### ISSUE THREAD

**Issue by TimouL** [vvbbnn00/WARP-Clash-API#167]
之前运行也没有问题 的，就这2天的事情，然后今天重新拉了最新的镜像，也还是这样
看了下日志，也没有看到哪里有报错的
![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/88996607/7b06be55-6874-4117-be38-cf390bf5789e)
请问是哪里配置不对吗？

**Comment by vvbbnn00** [comment]
可能是ip优选导致的问题，ip优选后，在结果中没有找到满足条件的节点（例如节点全部超时等），可以重新优选一下，或者将GitHub仓库的[/config/result.csv](https://github.com/vvbbnn00/WARP-Clash-API/blob/master/config/result.csv)和[/config/result_v6.csv](https://github.com/vvbbnn00/WARP-Clash-API/blob/master/config/result_v6.csv) 覆盖文件系统中被修改的文件

**Comment by 451008604** [comment]
推测是因为 result.csv 文件中IP列表的延迟为浮点类型导致，应该是代码中数值类型获取错误了：）
一个曲线救国的方案：**手动修改优选后的 result.csv，将文件中的 Latency 字段值修改为整数类型** 即可恢复正常

**Comment by wangyingang** [comment]
> 推测是因为 result.csv 文件中IP列表的延迟为浮点类型导致，应该是代码中数值类型获取错误了：） 一个曲线救国的方案：**手动修改优选后的 result.csv，将文件中的 Latency 字段值修改为整数类型**即可恢复正常 （此方法在 Mac M1 上亲测可行，但是在Linux中没出现订阅配置获取错误的问题）

果然如此！按照你的办法解决了此问题。

**Comment by saury** [comment]
> > 推测是因为 result.csv 文件中IP列表的延迟为浮点类型导致，应该是代码中数值类型获取错误了：） 一个曲线救国的方案：**手动修改优选后的 result.csv，将文件中的 Latency 字段值修改为整数类型**即可恢复正常 （此方法在 Mac M1 上亲测可行，但是在Linux中没出现订阅配置获取错误的问题）
> 
> 果然如此！按照你的办法解决了此问题。

实测有效，献上执行脚本。

```bash
#!/bin/bash

input_file="result.csv"
output_file="result_modified.csv"

# 创建新文件，并写入标题行
echo "IP:Port,Loss,Latency" > "$output_file"

# 读取每一行数据，并进行处理
while IFS=',' read -r ip_port loss latency; do
  # 提取整数部分
  latency_int=$(echo "$latency" | cut -d '.' -f 1)
  # 将处理后的数据写入新文件
  echo "$ip_port,$loss,$latency_int" >> "$output_file"
done < "$input_file"

echo "转换完成，结果保存到 $output_file"
```

**Comment by chptnt** [comment]
> 推测是因为 result.csv 文件中IP列表的延迟为浮点类型导致，应该是代码中数值类型获取错误了：） 一个曲线救国的方案：**手动修改优选后的 result.csv，将文件中的 Latency 字段值修改为整数类型**即可恢复正常 （此方法在 Mac M1 上亲测可行，但是在Linux中没出现订阅配置获取错误的问题）

求教，我也是mac M1，当我创建.env.local文件后，在终端无论执行 docker-compose up -d 命令，还是docker-compose exec warp-clash python3 app.py optimize
命令，都显示docker-compose.yaml: version is obsolete
failed to read /Users/chp/WARP-Clash-API/.env.local: line 1: unexpected character "{" in variable name "{\rtf1\ansi\ansicpg936\cocoartf2757"
不知道是什么问题，无论.env.local文件里是设置了SECRET_KEY还是其他环境变量，还是全部删除，留下空白文件，都会显示这些报错，但如果删掉.env.local文件，再执行上述命令，又会报错，找不到.env.local文件，请教大神，急盼回复

**Comment by 451008604** [comment]
> > 推测是因为 result.csv 文件中IP列表的延迟为浮点类型导致，应该是代码中数值类型获取错误了：） 一个曲线救国的方案：**手动修改优选后的 result.csv，将文件中的 Latency 字段值修改为整数类型**即可恢复正常 （此方法在 Mac M1 上亲测可行，但是在Linux中没出现订阅配置获取错误的问题）
> 
> 求教，我也是mac M1，当我创建.env.local文件后，在终端无论执行 docker-compose up -d 命令，还是docker-compose exec warp-clash python3 app.py optimize 命令，都显示docker-compose.yaml: version is obsolete failed to read /Users/chp/WARP-Clash-API/.env.local: line 1: unexpected character "{" in variable name "{\rtf1\ansi\ansicpg936\cocoartf2757" 不知道是什么问题，无论.env.local文件里是设置了SECRET_KEY还是其他环境变量，还是全部删除，留下空白文件，都会显示这些报错，但如果删掉.env.local文件，再执行上述命令，又会报错，找不到.env.local文件，请教大神，急盼回复

这种情况多半是因为你的.env.local文件内容写成了json格式
按照下面的格式直接写入文件，应该就可以了
👇👇👇👇👇👇从下面开始👇👇👇👇👇👇
SECRET_KEY=123456
SHARE_SUBSCRIPTION=True
👆👆👆👆👆👆到上面截止👆👆👆👆👆👆
