### ISSUE TITLE
账户信息不准确，需要我做什么吗？

### ISSUE THREAD

**Issue by lhuanyun** [vvbbnn00/WARP-Clash-API#168]
流量一直显示只有40个GB，
不明白是显示错误或者刷流量出现错误。

![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/20707383/50f6f66f-e75e-42de-9b8e-367f09bdefb5)

此外，需要更新docker吗？我是一个月前部署的服务？
现在的key是不是满大街都是，更新一次扔一次，。

**Comment by vvbbnn00** [comment]
可以更新到最新的docker，然后自行设置一个大流量key；由于目前使用的用户过多，免费代理池中的IP都已经达到了上限，因此如果不自己搭建代理池，很难通过程序获取流量了
