### ISSUE TITLE
显示WARNING - 429 Client Error: Too Many Requests for url: https://api.cloudflareclient.com/v0i2308311933/reg

### ISSUE THREAD

**Issue by Moe8383** [vvbbnn00/WARP-Clash-API#171]
运行一段时间后，日志显示：WARNING - 429 Client Error: Too Many Requests for url: https://api.cloudflareclient.com/v0i2308311933/reg
流量不再新增了

**Comment by Flyingpen** [comment]
同样遇到这个情况。

**Comment by vvbbnn00** [comment]
在通常情况下， 程序会从代理池中获取一个可用的代理，然后使用这个代理来访问cloudflare API，获取流量，然而由于目前使用的用户过多，免费代理池中的IP都已经达到了上限，因此很难再获取流量了；
您可以自行配置代理池，或者参照：https://github.com/vvbbnn00/WARP-Clash-API?tab=readme-ov-file#-%E8%BF%9B%E9%98%B6%E6%93%8D%E4%BD%9C
设置一个拥有大流量的 `LicenseKey`

**Comment by Moe8383** [comment]
> 您可以自行配置代理池，或者参照：https://github.com/vvbbnn00/WARP-Clash-API?tab=readme-ov-file#-%E8%BF%9B%E9%98%B6%E6%93%8D%E4%BD%9C
> 
> 设置一个拥有大流量的 `LicenseKey`

谢谢！请问host:port应该怎么填写？另外，优选IP时，需要断开代理吗？
