### ISSUE TITLE
[Bug] 手动优选ip报错

### ISSUE THREAD

**Issue by longstorying** [vvbbnn00/WARP-Clash-API#176]
执行 docker-compose exec warp-clash python3 app.py optimize
报下面的错
![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/37175458/d08c9108-d0c7-4d8f-b3f3-2ba08d1981a8)

**Comment by a13135556916** [comment]
我也遇到了这个问题

**Comment by zty0510** [comment]
me too

**Comment by vvbbnn00** [comment]
这是因为在优选IPv6时您的镜像不支持IPv6，如果您不需要使用该功能，无视即可，上面的IPv4优选时正常运行的

**Comment by longstorying** [comment]
> 这是因为在优选IPv6时您的镜像不支持IPv6，如果您不需要使用该功能，无视即可，上面的IPv4优选时正常运行的

好的一听说再看看日志好像是这么回事。多谢
