### ISSUE TITLE
[feature discuss]更好的节点名

### ISSUE THREAD

**Issue by CorrectRoadH** [vvbbnn00/WARP-Clash-API#18]
现在的随机节点名为`emoji CF-{color}`。意义较低，我在想能不能改成机场中更常见的格式，通过geoip拿到ip所在的位置，用`国旗  地址-CF-{随机}`的方式给节点一个更有意思的名字。🤔

可以ok的话，我可以提一个 PR

**Comment by vvbbnn00** [comment]
我觉得是一个很不错的提案！
