### ISSUE TITLE
一直报错是啥玩意？  mv: can't rename 'result.csv': No such file or directory

### ISSUE THREAD

**Issue by kilvn** [vvbbnn00/WARP-Clash-API#182]
![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/16423601/49f0d9c6-b7a2-491d-a823-518c50f1274d)

**Comment by kilvn** [comment]
最新docker镜像

**Comment by vvbbnn00** [comment]
你好，可以参考：https://github.com/vvbbnn00/WARP-Clash-API/issues/176

**Comment by kilvn** [comment]
前几天后面看到了这个issue，建议报错详细一点，不然看的一脸懵
