### ISSUE TITLE
[Bug] Ubuntu22.04 总是构建失败

### ISSUE THREAD

**Issue by pan-xi** [vvbbnn00/WARP-Clash-API#184]
**为了更快地定位问题并减少不必要的麻烦，请在发起issue前检查是否已有相关issue存在，
谢谢！**

**📜 检查表**

- [X] 我已了解目前issue主要处理`bug`和接收`feature request`
  ，其他类型的问题（如操作、配置问题，客户端问题等）应发布在[discussions](https://github.com/vvbbnn00/WARP-Clash-API/discussions)
  中，否则该issue可能被关闭。
- [ ] 我确认这是由本项目引起的bug，而非Cloudflare
  WARP自身服务限制、客户端不支持等其他原因造成的（若不确定，请同样发布在[discussions](https://github.com/vvbbnn00/WARP-Clash-API/discussions)）。
- [X] 我已核实该bug尚未在其他issue中被提及。

**Bug描述**

git以后进行docker compose，总是卡在构建python:3.11-alpine这一步

**复现步骤**

请提供复现bug所需的具体步骤，例如：

1. 执行命令 `docker-compose up -d`

**预期行为**

卡在构建python:3.11-alpine的中间过程

**截屏**

![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/99231533/f6fcf0c6-a790-4104-8579-6ef42e66dfaf)

**环境信息**

请准确填写相关信息，如是服务器端问题，请提供服务器环境信息：

- 系统版本：Ubuntu 22.04 LTS

**Comment by vvbbnn00** [comment]
你好，可能是您的服务器所处的网络环境不佳，导致镜像拉取失败，可以尝试更换 docker 镜像源

**Comment by pan-xi** [comment]
> 你好，可能是您的服务器所处的网络环境不佳，导致镜像拉取失败，可以尝试更换 docker 镜像源

好的，谢谢。有想过是镜像源的问题，但是其他操作都没问题，每次（我试了5次以上）都是同样的两个子项的构建那里卡住，就很奇怪，后来尝试直接dockerhub拉取，这个到没得问题
