### ISSUE TITLE
请教优选ip自定义的问题，

### ISSUE THREAD

**Issue by yantoumu** [vvbbnn00/WARP-Clash-API#186]
我自己有一个优选好的ip列表，要怎么导入到项目中使用，格式是啥

**Comment by vvbbnn00** [comment]
位于源代码路径下的`/config/result.csv`和`/config/result_v6.csv`，分别对应ipv4和ipv6。

格式可以参考：https://github.com/vvbbnn00/WARP-Clash-API/blob/master/config/result.csv
