### ISSUE TITLE
[Bug] 部署到zeabur且配置域名后，导入到clash失败，报错订阅链接格式错误

### ISSUE THREAD

**Issue by Gijela** [vvbbnn00/WARP-Clash-API#198]
**Bug描述**

如题，部署时没有设置访问密码，在zeabur上部署完成，设置域名后可以正常显示订阅配置页面，但是订阅链接无法导入到clash中。
<img width="848" alt="image" src="https://github.com/vvbbnn00/WARP-Clash-API/assets/82071209/c109e986-bad5-4f2e-a411-94524df4af4e">
<img width="403" alt="image" src="https://github.com/vvbbnn00/WARP-Clash-API/assets/82071209/3b188b9a-c6bd-42db-ac2b-d4b0959d6e22">

**Comment by Selenium39** [comment]
➕1

**Comment by gzxiexl** [comment]
+1

**Comment by vvbbnn00** [comment]
参考：https://github.com/vvbbnn00/WARP-Clash-API/discussions/86
