### ISSUE TITLE
[Bug] WARN[0000]

### ISSUE THREAD

**Issue by dwk601** [vvbbnn00/WARP-Clash-API#202]
WARN[0000] /home/dongwook/Project/WARP-Clash-API/docker-compose.yaml: `version` is obsolete 

I just run the project after the cloning process.

**Comment by vvbbnn00** [comment]
Simply remove the first line containing `version`, and it should be fine.

For more details, you can refer to: 
https://zenn.dev/harpseal/articles/8dc2602ffe3365
https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313
