### ISSUE TITLE
[Feature request]Please provide pure docker command

### ISSUE THREAD

**Issue by buhe** [vvbbnn00/WARP-Clash-API#204]
**To quickly locate the issue and reduce unnecessary trouble, please check if a
related issue already exists before creating a new one. Thank you!**

**📜 Checklist**

- [x] I understand that the current issue mainly handles `bugs` and
  accepts `feature requests`. Other types of issues (such as operational,
  configuration issues, client issues, etc.) should be posted
  in [discussions](https://github.com/vvbbnn00/WARP-Clash-API/discussions),
  otherwise, the issue may be closed.
- [x] I have verified that this `feature request` has not been mentioned in
  other issues.
- [ ] (Optional) For this `Feature Request`, I have already implemented a
  solution and opened a related `Pull Request` (thank you for your
  contribution!)

**Is this Feature Request related to a problem in the current project? If yes,
please describe below:**

Such as
 ```
docker run xxx
```

**Comment by a5412398** [comment]
You can give this a try：docker run -p 21001:3000 -e SECRET_KEY=123456 -v ./account:/app/account -v ./logs:/app/logs vvbbnn00/warp-clash-api:latest

**Comment by buhe** [comment]
Thanks.
