### ISSUE TITLE
我不需要刷流量，如何导入一批已有的wg-config.conf

### ISSUE THREAD

**Issue by coulsontl** [vvbbnn00/WARP-Clash-API#206]
如题，我不想让docker新建一个key去慢慢刷流量，如何导入我已有的一批刷好流量的wg-config.conf呢？

类型这样的 wg-config.conf

[Interface]
PrivateKey = kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx4=
Address = 172.16.0.2/32, 2606:4700:110:8436:5647:b174:13f1:d192/128
DNS = 1.1.1.1, 1.0.0.1, 2606:4700:4700::1111, 2606:4700:4700::1001
MTU = 1280
[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0
AllowedIPs = ::/0
Endpoint = engage.cloudflareclient.com:2408

**Comment by a5412398** [comment]
![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/6203439/f55cead4-8c73-41a6-98d8-1fb0fe2f90ec)

**Comment by vvbbnn00** [comment]
可以修改生成的account.json文件，然后将`GET_WARP_DATA_INTERVAL`设置为`0`以关闭流量刷取

**Comment by coulsontl** [comment]
-
