### ISSUE TITLE
更新license_key报错

### ISSUE THREAD

**Issue by a5412398** [vvbbnn00/WARP-Clash-API#208]
![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/6203439/d37fb3f2-59ff-4cdc-9c10-96095ed2c0b1)

curl -X POST http://192.168.0.3:21001/api/account/update_license?key=psj1122fg001 -H "Content-Type: appli
cation/json" -d "{"license_key": "Kp5fb793-0KG4E83s-1ZY9B6r2"}"

命令没问题啊，为啥提示这个？

**Comment by chptnt** [comment]
请问你解决了吗，我更新自己的license_key 后报错：{"code":403,"message":"Unauthorized"}

**Comment by chptnt** [comment]
我已经解决了，你的命令应该错了，update_license?key=psj1122fg001，这一块你就保持默认给你的命令（你的命令中修改了?key=psj1122fg001），我之前的错误是因为我设置了secret_key，所以导致更新没有权限，因为命令中没有设置secret_key

**Comment by a5412398** [comment]
现在命令倒是跑成功，没有错误提示了，但是好像在这个账户信息里面看到的    "license_key"  字段并没有发生更改，    "updated_at"  时间也没变，重启了docker也不行，不知道啥情况，只能将就用吧.
![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/6203439/20c65889-a74b-4ab8-bed5-650568089938)

**Comment by a5412398** [comment]
换成这个命令，执行成功了  curl -v -k -X POST https://d.******.xyz:82/api/account/update_license?key=ps*****g001 -H "Content-Type: application/json" -d "{\"license_key\": \"Kp5fb7*********Y9B6r2\"}"    真不容易
