### ISSUE TITLE
下载配置文件报错

### ISSUE THREAD

**Issue by ksi1110** [vvbbnn00/WARP-Clash-API#211]
部署compose后，看日志刷新流量正常，但在页面下载配置文件时报错，日志如下，本地环境是debian11，python版本是3.9。

2024-05-28 04:04:11,798 - ERROR - Exception on /api/wireguard [GET]
warp-clash-1  | Traceback (most recent call last):
warp-clash-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
warp-clash-1  |     response = self.full_dispatch_request()
warp-clash-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warp-clash-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
warp-clash-1  |     rv = self.handle_user_exception(e)
warp-clash-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warp-clash-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
warp-clash-1  |     rv = self.dispatch_request()
warp-clash-1  |          ^^^^^^^^^^^^^^^^^^^^^^^
warp-clash-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
warp-clash-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
warp-clash-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warp-clash-1  |   File "/app/services/web_service.py", line 66, in decorated_function
warp-clash-1  |     return f(*args, **kwargs)
warp-clash-1  |            ^^^^^^^^^^^^^^^^^^
warp-clash-1  |   File "/app/services/web_service.py", line 26, in decorated_function
warp-clash-1  |     return f(*args, **kwargs)
warp-clash-1  |            ^^^^^^^^^^^^^^^^^^
warp-clash-1  |   File "/app/services/web_service.py", line 121, in http_wireguard
warp-clash-1  |     fileData = generate_Wireguard_subFile(account, logger, best=best)
warp-clash-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warp-clash-1  |   File "/app/services/subscription.py", line 77, in generate_Wireguard_subFile
warp-clash-1  |     entrypoints = get_entrypoints()
warp-clash-1  |                   ^^^^^^^^^^^^^^^^^
warp-clash-1  |   File "/app/utils/entrypoints.py", line 43, in get_entrypoints
warp-clash-1  |     reload_entrypoints()
warp-clash-1  |   File "/app/utils/entrypoints.py", line 25, in reload_entrypoints
warp-clash-1  |     delay = int(row[2].replace('ms', ''))
warp-clash-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by vvbbnn00** [comment]
看起来好像在解析接入点延迟的时候出现了一些错误，方便查看一下`result.csv`和`result_v6.csv`两个文件吗

**Comment by ksi1110** [comment]
> 看起来好像在解析接入点延迟的时候出现了一些错误，方便查看一下`result.csv`和`result_v6.csv`两个文件吗

sorry，已经解决了，rebuild后可以正常使用
