### ISSUE TITLE
[Bug] 自動切換IP的問題

### ISSUE THREAD

**Issue by CattleZoe** [vvbbnn00/WARP-Clash-API#216]
感謝作者的付出,clash verg最新版工作正常
但是有個問題沒法解決.

就是我選擇了某個代理ip后,例如美國的代理ip,我訪問ip.sp或者tiktok的時候,clash自動切換到離我最近的IP,例如HK,

我使用其他cf warp優選訂閲地址沒有這個問題,不會自動選擇最近的ip

是不是我沒有做好某個參數設定?

感謝

**Comment by CattleZoe** [comment]
另外,我切換了 best=false,best=true的效果也是一樣的

**Comment by vvbbnn00** [comment]
你好，感謝您的支持。從原理上來說，warp會就近為您分配出口IP，可參考： https://github.com/vvbbnn00/WARP-Clash-API/issues/65
