### ISSUE TITLE
优选IP的结果不会更换

### ISSUE THREAD

**Issue by violets007** [vvbbnn00/WARP-Clash-API#34]
一直是项目copy下来的结果,不会替换csv

<img width="1448" alt="image" src="https://github.com/vvbbnn00/WARP-Clash-API/assets/20490066/d8cfc01c-a853-429e-94b2-de90df84a7e2">
<img width="857" alt="image" src="https://github.com/vvbbnn00/WARP-Clash-API/assets/20490066/8dce10b9-2834-4849-93dc-a111ede498f1">

**Comment by hahach** [comment]
这是一个bug。它的优选ip列表文件result.csv在config目录下，但是直接运行的话是在默认的 /app目录下运行的，生成的result.csv文件也在这，所以不会替换。
我的解决办法是修改/scripts/get_entrypoints.sh 在函数  endpoint4(){   的第一行增加一个进入目录即可  cd /app/config
