### ISSUE TITLE
修改 更新订阅随机节点的数量 超过10， 更新订阅报错

### ISSUE THREAD

**Issue by byxlle** [vvbbnn00/WARP-Clash-API#35]
![Screenshot_20240205-184656](https://github.com/vvbbnn00/WARP-Clash-API/assets/46641219/6e1042bd-499b-40d8-9c88-e9d5886286b9)

**Comment by vvbbnn00** [comment]
看起来是随机节点名的时候重复了，稍后会修复这个问题，现在可以尝试重新获取一下订阅，或者把randomName设置为false

**Comment by byxlle** [comment]
好的，感谢。
