### ISSUE TITLE
DO_GET_WARP_DATA=False 似乎无效

### ISSUE THREAD

**Issue by hahach** [vvbbnn00/WARP-Clash-API#39]
有个奇怪的地方没搞懂，我明明给了 DO_GET_WARP_DATA=False 但是容器启动后还是会刷流量。我现在的做法是直接把run.sh里的 python3 app.py background& 注释掉了。不清楚是不是bug

_Originally posted by @hahach in https://github.com/vvbbnn00/WARP-Clash-API/discussions/38#discussioncomment-8519482_

**Comment by hahach** [comment]
另外，优选功能有bug， 运行get_entrypoints.sh的工作目录在/app，二result.csv在/app/config下，因此优选ip是不会替换的。详见

#[https://github.com/vvbbnn00/WARP-Clash-API/issues/34#issuecomment-1953390623](url)

**Comment by vvbbnn00** [comment]
相关问题已经定位，后续会修复，感谢您的支持！
