### ISSUE TITLE
sub-store无法识别订阅地址

### ISSUE THREAD

**Issue by cikichen** [vvbbnn00/WARP-Clash-API#40]
想通过sub-store来统一管理订阅，但是发现不能识别

**Comment by vvbbnn00** [comment]
你好，您可以尝试在链接中添加参数`includeUnsupportedProxy=true`，若问题仍然存在，劳烦您提供更详细的错误信息，以便问题的排查，谢谢

**Comment by cikichen** [comment]
> 你好，您可以尝试在链接中添加参数`includeUnsupportedProxy=true`，若问题仍然存在，劳烦您提供更详细的错误信息，以便问题的排查，谢谢

我用公益服了
