### ISSUE TITLE
请问：自己的VPS通过Docker搭建订阅，怎么生成"小火箭"的订阅？

### ISSUE THREAD

**Issue by showlee** [vvbbnn00/WARP-Clash-API#43]
如题：

**Comment by showlee** [comment]
如题：
请问：自己的VPS通过Docker搭建订阅，怎么生成"小火箭"的订阅？
谢谢！

**Comment by CorrectRoadH** [comment]
自己搭建时，这个clash的订阅就是小火箭用的订阅。
![CleanShot 2024-02-21 at 11 10 41@2x](https://github.com/vvbbnn00/WARP-Clash-API/assets/29306285/cc8547fb-ab28-4027-98ea-10ec1505e904)

**Comment by showlee** [comment]
谢谢！大意了，我看到是Surge,所以没去添加了试试。

**Comment by zachzhao1984** [comment]
我用这个已经搭好的服务 https://tofree.zeabur.app/  获取的订阅链接，速度好像不太行

**Comment by Jerrychenshen** [comment]
楼主，你自己域名是怎么设置的，是反代吗？
