### ISSUE TITLE
请问是否支持定期优选IP？

### ISSUE THREAD

**Issue by OwnerCM** [vvbbnn00/WARP-Clash-API#44]
如题：请问是否支持定期优选IP？还是第一次启动程序后，后续只能手动优选IP？

**Comment by vvbbnn00** [comment]
目前仅支持手动优选IP，若您希望定期对IP进行优选，目前可以使用计划任务来实现该需求，未来的更新中可能也会加入这一功能。

**Comment by hahach** [comment]
镜像是基于alpine构建的，我看了是带crond的。 按以下步骤来做可以实现：
一、
a) 会用vi的，直接docker exec -it 你容器名 bash 进入容器，然后直接crontab -e 编辑增加crond任务 
例如：下面是每30分钟优选一次

*/30 * * * * cd /app && python3 app.py optimize

b) 不会用vi的，你可以cp /var/spool/cron/crontabs/root /app/config/root 这样crond的配置文件就复制到config目录下了，你可以在宿主机里编辑crond的配置文件，增加上面那一行。然后再在容器里复制回去。

二、
最后就是增加crond的运行。 在容器里编辑 /app/scripts/run.sh 文件， 在python3 那两行前，增加一个crond -f & （前台运行可以查看输出） 不会容器内用vi的，用之前的方法搞到宿主机编辑。
编辑完后重启容器即可

当然这个是临时的方法。再重新pull镜像后会失效。要注意这点。 或者可以等作者添加这个功能。
