### ISSUE TITLE
关于 Dockerfile 的 FROM --platform

### ISSUE THREAD

**Issue by LuGHuaaa** [vvbbnn00/WARP-Clash-API#5]
```FROM --platform=linux/amd64 python:3.11-alpine```
Dockerfile 指定了 platform 是不是不太好, 很多场景不是 linux amd64 的.

**Comment by LuGHuaaa** [comment]
另外 RUN apk add 缺少了  build-base libffi-dev openssl-dev, 可能导致 pip install 失败

**Comment by vvbbnn00** [comment]
感谢您的建议，目前代码已做相应优化。
