### ISSUE TITLE
社区实例不可用

### ISSUE THREAD

**Issue by shunia** [vvbbnn00/WARP-Clash-API#50]
刚看到项目尚未自行部署，想尝试一下社区实例看看效果。用安卓端Clash Meta导入配置后，可测延迟正常，但是无法打开墙后网页和应用。想确认一下可能是什么问题？

**Comment by CorrectRoadH** [comment]
已重启社区实例，我这边测试一下，重新订阅信息之后。暂时是能跑的，后续会定位一下具体的问题。
![CleanShot 2024-02-23 at 10 37 50@2x](https://github.com/vvbbnn00/WARP-Clash-API/assets/29306285/9d16c46e-295b-406a-afa5-ef9b67e4ffda)

**Comment by hahach** [comment]
之前我以为可能是wireguard的dns问题。

前两天我改了作者的配置模板文件，把proxies的模板里面远程dns打开了并且配置了 1.1.1.1的服务端dns。 后面还把warp+改成了Zero truth。还有clash 本地dns配置里面默认dns增加了 1.1.1.1。 还在本机上重新优选过ip。 就解决了。

以上操作都有可能是解决的问题。
不过今天重新拉镜像，默认配置模板重置后，也还能访问。
那我这里的情况就只剩下：
1、账户类型 warp+  vs Zero truth
2、clash 本地设置dns
3、优选ip

其中1、3我觉得可能性较低。

**Comment by shunia** [comment]
我这会儿更新订阅后，问题还是存在。

Clash Meta的调试日志显示 `Retrying handshake because we stopped hearing back after 15 seconds`，应该是服务端有点问题？

**Comment by shunia** [comment]
> 我这会儿更新订阅后，问题还是存在。
> 
> Clash Meta的调试日志显示 `Retrying handshake because we stopped hearing back after 15 seconds`，应该是服务端有点问题？

还有一条dns的报错 `re-creating the http client due to requesting ****/dns-query****: Get ****/dns-query****: context deadline exceeded`，很符合 @hahach 的说法。不过这块儿我不太懂，所以无法确定。

**Comment by CorrectRoadH** [comment]
> 之前我以为可能是wireguard的dns问题。
> 
> 前两天我改了作者的配置模板文件，把proxies的模板里面远程dns打开了并且配置了 1.1.1.1的服务端dns。 后面还把warp+改成了Zero truth。还有clash 本地dns配置里面默认dns增加了 1.1.1.1。 还在本机上重新优选过ip。 就解决了。
> 
> 以上操作都有可能是解决的问题。 不过今天重新拉镜像，默认配置模板重置后，也还能访问。 那我这里的情况就只剩下： 1、账户类型 warp+ vs Zero truth 2、clash 本地设置dns 3、优选ip
> 
> 其中1、3我觉得可能性较低。

确实有可能。因为我测试的是surge，surge的节点有给出dns是1.1.1.1 。而clash的配置没有显式的给出。🤔

**Comment by CorrectRoadH** [comment]
社区实例稍后会同步代码，解决这个问题👌

**Comment by CorrectRoadH** [comment]
社区实例已更新到最新的代码。该issue可关闭 @vvbbnn00

**Comment by shunia** [comment]
我这里测试结果还是一样的，似乎并没有修复。

**Comment by CorrectRoadH** [comment]
> 我这里测试结果还是一样的，似乎并没有修复。

好的，我稍后再测试一下🤔

**Comment by UncleUncleWang** [comment]
目前貌似并没有修复
