### ISSUE TITLE
Surge 订阅里面的节点无效

### ISSUE THREAD

**Issue by treasunew** [vvbbnn00/WARP-Clash-API#54]
所有节点信息除了 MTU 有信息，其他的全是空白
是需要配置其他环境变量吗
![IMG_2543](https://github.com/vvbbnn00/WARP-Clash-API/assets/104483693/e322ed48-5b58-4ea8-bf9a-cd760f8a8f70)

**Comment by vvbbnn00** [comment]
是直接使用Surge的订阅链接进行订阅的吗？

**Comment by CorrectRoadH** [comment]
是self host的吗? 可以试试`https://subs.zeabur.app/surge`。如果这个也不能用的话，可能是对应surge版本问题，需要进一步调研。在我的 surge for ios上，是能正常使用的🤔

**Comment by treasunew** [comment]
> 是self host的吗? 可以试试`https://subs.zeabur.app/surge`。如果这个也不能用的话，可能是对应surge版本问题，需要进一步调研。在我的 surge for ios上，是能正常使用的🤔

已经解决了，新建订阅，不能当策略组用，谢谢大佬，提供优秀的项目！！！

**Comment by treasunew** [comment]
> 是直接使用Surge的订阅链接进行订阅的吗？

是的
