### ISSUE TITLE
请教一下手动优选IP问题

### ISSUE THREAD

**Issue by lainbo** [vvbbnn00/WARP-Clash-API#55]
请问一下, 如果在海外的服务器上使用`docker-compose exec warp-clash python3 app.py optimize`进行手动IP优选, 得到的优选结果是针对这台海外服务器IP的优选结果吗? 还是针对中国大陆的优选结果?

**Comment by vvbbnn00** [comment]
优选是针对当前服务器网络环境进行优选的结果，若您需要针对自己的网络环境进行优选，可以先在本地跑一下，然后把`result.csv`复制到海外服务器。
