### ISSUE TITLE
设置自己的LicenseKey时, 返回400错误

### ISSUE THREAD

**Issue by lainbo** [vvbbnn00/WARP-Clash-API#59]
**出现的问题**
当我尝试设置自己的LicenseKey时, 返回了
```
<!doctype html>
<html lang=en>
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
curl: (3) URL rejected: Malformed input to a URL function
```

**我操作的步骤**
1. 拉取最新的代码
2. `.env.local`内容如下
```
PUBLIC_URL=*******
REOPTIMIZE_INTERVAL=3600
SHARE_SUBSCRIPTION=True
DO_GET_WARP_DATA=False
SECRET_KEY=*******
```
3. 使用`docker-compose down && docker-compose up -d --build`重新运行
4. 使用`curl -X POST https://我的域名/api/account/update_license?key=******* -H "Content-Type: application/json" -d "{\"license_key\": \"Ed1964AJ-7exRw182-4308EKgH\"}"`
5. 得到了400的返回

**Comment by vvbbnn00** [comment]
你好，使用该`LicenseKey`时返回如下错误：
```
{'result': None, 'success': False, 'errors': [{'code': 1056, 'message': 'Too many connected devices.'}], 'messages': []}
```
请检查您的`LicenseKey`是否已经绑定了5个及以上设备

**Comment by lainbo** [comment]
> 你好，使用该`LicenseKey`时返回如下错误：
> 
> ```
> {'result': None, 'success': False, 'errors': [{'code': 1056, 'message': 'Too many connected devices.'}], 'messages': []}
> ```
> 
> 请检查您的`LicenseKey`是否已经绑定了5个及以上设备

请问使用什么方式可以校验一个LicenseKey能否被本项目使用呢, 或者说你的这个返回值是如何请求到的

**Comment by vvbbnn00** [comment]
https://github.com/vvbbnn00/WARP-Clash-API/blob/fe15f01d3ecff0a197d3085b1294b650f66a393a/services/cloudflare.py#L141

通过请求这个接口可以更换LicenseKey，由于我这里直接`response.raise_for_status()`了，所以状态码如果>=400就直接抛异常了😂
后续更新我在日志里加一下错误信息
