### ISSUE TITLE
求构建好的镜像

### ISSUE THREAD

**Issue by kokojacket** [vvbbnn00/WARP-Clash-API#6]
您好，我构建镜像没有成功，求一个已经构建好的镜像~

**Comment by mizb** [comment]
我也想要。。。。

**Comment by xunilalala** [comment]
你们完全可以打开看一下dockerfile；你们打开之后就会发现，就是安装python环境，然后pip安装依赖，最后运行run.sh（这个也完全可以打开看一下，就几句命令）;不要总想着伸手，要学会自己解决问题

**Comment by xunilalala** [comment]
> 我也想要。。。。



> 您好，我构建镜像没有成功，求一个已经构建好的镜像~

 你们完全可以打开看一下dockerfile;你们打开之后就会发现，就是安装python环境，然后pip安装依赖，最后运行 run.sh（这个也完全可以打开看一下，就几句命令）;不要总想着伸手，要学会自己解决问题
