### ISSUE TITLE
群晖docker可以启动，订阅地址不能用显示 code 403 forbidden

### ISSUE THREAD

**Issue by RocMWH** [vvbbnn00/WARP-Clash-API#62]
![截屏2024-02-25 22 17 55](https://github.com/vvbbnn00/WARP-Clash-API/assets/161224096/fe22d5da-252e-40c5-b930-d0cd6814c170)
 之前没报连接过多，订阅地址也不能用。导入小火箭就是 forbidden

**Comment by vvbbnn00** [comment]
429问题参考 #7 
当然，若您的账户流量达到上限（也就是24T），也会报同样的错误。

关于订阅地址不能用，具体是什么情况呢？是如何操作的，访问订阅连接时提示什么错误

**Comment by RocMWH** [comment]
![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/161224096/c6cc3902-ac3f-4155-be78-628c9d2ee274)
![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/161224096/b3cc95eb-ceb7-4774-b4ac-7ea5ae7978bf)
![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/161224096/1f12eaec-0ab8-4780-8019-858eded18015)
流量还有24.6pb可以在cloudflare one中正常使用，浏览器打开容器地址后，输入key，再到小火箭或者其它客户端都保错。
另外账户信息中也保错，提示没有权限。

**Comment by vvbbnn00** [comment]
你好，请检查一下您的secret key是否输错了

**Comment by RocMWH** [comment]
不会的
![截屏2024-02-26 12 32 24](https://github.com/vvbbnn00/WARP-Clash-API/assets/161224096/cc40d982-edd1-4b2b-bd21-1ffb6a2edf98)

**Comment by vvbbnn00** [comment]
secretkey是自己设置的，和licensekey不同，详见readme

**Comment by RocMWH** [comment]
好的 readme我看了 “secretkey为可选项 不需要分享的话 可以不设置 订阅链接也可以用” 但还是一样，forbidden

**Comment by vvbbnn00** [comment]
> 好的 readme我看了 “secretkey为可选项 不需要分享的话 可以不设置 订阅链接也可以用” 但还是一样，forbidden

emm 你看看你的环境变量中 SECRET_KEY 的值是否有内容呢 理论上来说 SECRET_KEY 为空的情况不会存在403错误的

**Comment by vvbbnn00** [comment]
> 环境变量 0或者无 都不行 其它变量都是参考这里的默认值

`无`是指**不设置**这个环境变量 而不是将值设置成`无`哦
`0` 也是同理 设置了以后 SECRET_KEY 应该是 `0`了

**Comment by RocMWH** [comment]
哈哈哈 我傻X了 可以关闭这个issues了
