### ISSUE TITLE
Clash配置类型错误

### ISSUE THREAD

**Issue by Emmeet** [vvbbnn00/WARP-Clash-API#64]
unsupport proxy type: wireguard

**Comment by Emmeet** [comment]
![Uploading PixPin_2024-02-26_14-33-11.png…]()

**Comment by abstain23** [comment]
同样的错误

**Comment by vvbbnn00** [comment]
参考 https://github.com/vvbbnn00/WARP-Clash-API/discussions/86

**Comment by Emmeet** [comment]
> 同样的错误

Clash版本的问题
