### ISSUE TITLE
无法访问gpt

### ISSUE THREAD

**Issue by kingui1106** [vvbbnn00/WARP-Clash-API#65]
gpt无法访问，使用的社区实例
clash-verge-rev，规则模式
```
Unable to load site

Please try again later. If you are using a VPN, try turning it off. Check the [status page](https://status.openai.com/) for information on outages.
```

**Comment by vvbbnn00** [comment]
这个和出口IP有关，很可能你分配到的出口IP是香港的，所以就无法解锁ChatGPT了
通常情况下来说，WARP的出口IP都是就近分配的

**Comment by mengdahuang** [comment]
好奇这个应该是在VPS上部署合理还是在本地（境内）部署合理？

**Comment by ywythu** [comment]
请问所以像c站https://civitai.com/这种连不上也是因为类似的出口IP原因吗，我google之类的网站都能登上，c站怎么都连不上

**Comment by zy111x** [comment]
我也是，chatgpt claude等主流AI无法使用
