### ISSUE TITLE
请求过多

### ISSUE THREAD

**Issue by kokojacket** [vvbbnn00/WARP-Clash-API#7]
![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/74887370/d8b8ce82-d0df-42ec-9306-506a067f9777)

**Comment by vvbbnn00** [comment]
这是代理IP被频繁使用导致的，您可以尝试自行搭建代理IP池（详情参照[proxy_pool](https://github.com/jhao104/proxy_pool)），在搭建完毕后，您可以将[utils/proxy.py](https://github.com/vvbbnn00/WARP-Clash-API/tree/master/utils/proxy.py)文件中的代理池地址（`https://getproxy.bzpl.tech/get/`）替换为自己的代理池。

**Comment by kokojacket** [comment]
@vvbbnn00 请问是直接部署proxy_pool之后，修改utils/proxy.py文件，让后重启容器吗

**Comment by vvbbnn00** [comment]
若您使用的是旧版的代码，建议您在编译前修改好文件；不过，更推荐使用刚刚更新的版本，在该版本中，只需配置`PROXY_POOL_URL`环境变量即可实现修改代理IP池的URL。

**Comment by kokojacket** [comment]
如果不需要刷取流量，是否就不需要部署proxy_pool了，DO_GET_WARP_DATA=False就可以了

**Comment by vvbbnn00** [comment]
是的

**Comment by fatinghenji** [comment]
自行搭建后报错如下：
```
2024-01-12 13:12:19 warp-clash-1  | 2024-01-12 05:12:19,948 - INFO - Get current account
2024-01-12 13:12:19 warp-clash-1  | 2024-01-12 05:12:19,953 - INFO - WORK ON ID: 51696d78-e633-438c-b3fc-1c0b59d26a49
2024-01-12 13:12:19 warp-clash-1  | 2024-01-12 05:12:19,955 - WARNING - Failed to get account from Cloudflare.
2024-01-12 13:12:19 warp-clash-1  | 2024-01-12 05:12:19,956 - WARNING - HTTPConnectionPool(host='127.0.0.1', port=5010): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd1a6c01cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by vvbbnn00** [comment]
是在docker环境中运行的吗？如果是docker的话，需要注意网络环境的配置，不能直接访问127.0.0.1

**Comment by fatinghenji** [comment]
> 是在docker环境中运行的吗？如果是docker的话，需要注意网络环境的配置，不能直接访问127.0.0.1

是的，是docker新手，可以麻烦您将下应该如何填写吗？

**Comment by vvbbnn00** [comment]
如果使用docker-compose，可以在我的docker-compose下面，合并proxy_pool的服务：
```yaml
  proxy_pool:
    image: "jhao104/proxy_pool"
    container_name: proxy_pool
    ports:
      - "5010:5010"
    links:
      - proxy_redis
    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"
  proxy_redis:
    image: "redis"
    container_name: proxy_redis
```

然后，代理池填写`proxy_pool:5010`即可

或者，您也可以尝试使用`host.docker.internal`指向本机IP，即代理池填写`host.docker.internal:5010`，这种情况下，需要在服务下配置：
```yaml
extra_hosts:
  - 'host.docker.internal:host-gateway'
```
例如：
```yaml
version: '3.9'
services:
  myservice:
    # ...
    extra_hosts:
      - host.docker.internal:host-gateway
```

**Comment by fatinghenji** [comment]
> 如果使用docker-compose，可以在我的docker-compose下面，合并proxy_pool的服务：
> 
> ```yaml
>   proxy_pool:
>     image: "jhao104/proxy_pool"
>     container_name: proxy_pool
>     ports:
>       - "5010:5010"
>     links:
>       - proxy_redis
>     environment:
>       DB_CONN: "redis://@proxy_redis:6379/0"
>   proxy_redis:
>     image: "redis"
>     container_name: proxy_redis
> ```
> 
> 然后，代理池填写`proxy_pool:5010`即可
> 
> 或者，您也可以尝试使用`host.docker.internal`指向本机IP，即代理池填写`host.docker.internal:5010`，这种情况下，需要在服务下配置：
> 
> ```yaml
> extra_hosts:
>   - 'host.docker.internal:host-gateway'
> ```
> 
> 例如：
> 
> ```yaml
> version: '3.9'
> services:
>   myservice:
>     # ...
>     extra_hosts:
>       - host.docker.internal:host-gateway
> ```

谢谢您的解答，我通过查询`proxy_pool`容器的ip地址的方法解决了。

**Comment by fatinghenji** [comment]
@vvbbnn00 麻烦您解答下。谢谢。

**Comment by vvbbnn00** [comment]
需要按照您部署的项目而定，如果您的项目中，获取代理的请求路径是`/get`，那么就填写`http://proxy_pool:5010/get`
