### ISSUE TITLE
生成的订阅在PC端用clash-verge-rev正常，在手机端clashmeta怎么都用不起来。

### ISSUE THREAD

**Issue by jjjyyyllll** [vvbbnn00/WARP-Clash-API#74]
clash-verge-rev ：https://github.com/clash-verge-rev/clash-verge-rev
clashmeta：https://github.com/MetaCubeX/ClashMetaForAndroid

手机端直接就无反应

**Comment by vvbbnn00** [comment]
问题确实存在，经过测试，发现将节点配置中的`dns`删除后便可正常访问。
为了保证PC端的稳定性，稍后的更新将只针对安卓端clash meta进行。

**Comment by Cloud0310** [comment]
最新版本在选择 proxies only 时复现上述 bug ，希望添加一个 url param 来决定是否返回含 dns 的字段
![Screenshot_20240325-012414_Chrome](https://github.com/vvbbnn00/WARP-Clash-API/assets/60375730/8eca3b56-247e-4831-9ab7-89cb4af62dea)
