### ISSUE TITLE
支持指定使用ipv6的endpoint?

### ISSUE THREAD

**Issue by KiriKira** [vvbbnn00/WARP-Clash-API#82]
目前在上海电信和上海移动有ipv6的情况下实测使用ipv6的endpoint效果更好,连接更稳定. 能否支持指定只使用 ipv6 endpoint?
https://gitlab.com/Misaka-blog/warp-script/-/tree/main/files/warp-yxip 这个project中有一些ipv6的参考

**Comment by vvbbnn00** [comment]
可以的，由于我这边的环境不支持ipv6，后期在ipv6环境下测试通过后，会更新相应功能。

**Comment by offzen** [comment]
我的Ipv4完全不能连接，增加ipv6（（172.16.0.2/32,2606:4700:110:8149:b1e0:8a01:e15b:f730/128））
，并设置endpoint也是v6地址，但默认是还是会连ipv4？有没有临时修复的办法？

![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/130923201/d520c850-d8ce-4c40-8283-02acaf21cf51)
